# Build Stage
FROM debian:buster as build
RUN apt-get update && apt-get install -y ca-certificates
WORKDIR /app

# Final Stage
FROM scratch

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs
COPY --from=build /app/dist/binaries/fritzbox-graphite-linux-arm64 /app/fritzbox-graphite

ENTRYPOINT ["/app/fritzbox-graphite"]
CMD ["-c /app/fritzbox-graphite.json"]