# Build Stage
FROM debian:buster as build
RUN apt-get update && apt-get install -y ca-certificates
WORKDIR /app

# Final Stage
FROM scratch

ENTRYPOINT ["/app/fritzbox-graphite"]
CMD ["-c /app/fritzbox-graphite.json"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs
COPY --from=build /etc/mime.types /etc/
COPY dist/binaries/fritzbox-graphite-*-linux-arm64 /app/fritzbox-graphite
